version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: ${GITLAB_HOSTNAME}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://${GITLAB_HOSTNAME}"
        gitlab_rails['time_zone'] = 'Asia/Tokyo'
        gitlab_rails['backup_keep_time'] = 604800
        # メール設定
        gitlab_rails['smtp_enable'] = ${SMTP_ENABLED}
        gitlab_rails['smtp_address'] = "${SMTP_HOST}"
        gitlab_rails['smtp_port'] = ${SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${SMTP_USER}"
        gitlab_rails['smtp_password'] = "${SMTP_PASS}"
        gitlab_rails['smtp_domain'] = "${SMTP_DOMAIN}"
        gitlab_rails['smtp_authentication'] = "${SMTP_AUTHENTICATION}"
        gitlab_rails['smtp_enable_starttls_auto'] = ${SMTP_ENABLE_STARTTLS_AUTO}
        gitlab_rails['gitlab_email_from'] = "${SMTP_USER}"
        # GitLab Workhorse設定
        gitlab_workhorse['listen_network'] = "tcp"
        gitlab_workhorse['listen_addr'] = "0.0.0.0:8181"
        # Nginxの設定
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        # SSHの設定
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
      - './backups:/var/opt/gitlab/backups'
    shm_size: '256m'
    deploy:
      resources:
        limits:
          memory: ${GITLAB_MEMORY_LIMIT}
        reservations:
          memory: '2048M'
    networks:
      - gitlab-network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    depends_on:
      - gitlab
    volumes:
      - './runner:/etc/gitlab-runner'
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab-network

networks:
  gitlab-network:
    driver: bridge
